# Generated by Django 5.0.2 on 2024-03-10 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_id_alter_conversationmessage_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('-created_at',)},
        ),
    ]
