# Generated by Django 5.0.2 on 2024-03-07 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_friends_friendshiprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='create_for',
            new_name='created_for',
        ),
    ]
