# Generated by Django 5.0.2 on 2024-03-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_firends_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firends_count',
            new_name='friends_count',
        ),
    ]
