# Generated by Django 5.0.2 on 2024-03-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
