# Generated by Django 5.0.2 on 2024-03-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='post_id',
            new_name='post',
        ),
    ]
