# Generated by Django 5.0.2 on 2024-03-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_comment_count_comment_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comment_count',
            new_name='comments_count',
        ),
    ]
