# Generated by Django 5.0.2 on 2024-03-11 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_trends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trends',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
