# Generated by Django 5.0.2 on 2024-03-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_trends_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trends',
        ),
    ]
