# Generated by Django 5.0.2 on 2024-03-11 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_delete_trends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=250)),
                ('occurences', models.IntegerField()),
            ],
        ),
    ]
