# Generated by Django 5.0.2 on 2024-03-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
